version: '3.0'

services:
  master:
    image: locustio/locust
    ports:
      - 8089:8089
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://192.168.31.244:8080/api/v1/app